### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yiru1018**
施怡如

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URLs for testing.

**Comment by yiru1018** [comment]
> I need your online URLs for testing.

http://18.177.180.125:3000/api/attractions?page=０
http://18.177.180.125:3000/api/attractions?page=0&keyword=公園
http://18.177.180.125:3000/api/attraction/29

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. "nextPage" of http://18.177.180.125:3000/api/attractions?page=0&keyword=%E5%85%AC%E5%9C%92 should be null.
2. "image" of your response should be an array contains image URLs separately, not a string.

Fix issues, create new commits, and ask me to review again from right side in this page.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
